#!groovy
node {

    def err = null
    currentBuild.result = "SUCCESS"

    try {
       stage 'Checkout'
            checkout scm
            
       stage 'Deploy'
            echo 'Install test Environment'
            sh 'qual-stress-monitoring/deploytestenv.sh'
       stage 'Stress Mon Manager API '
            echo 'Send 1000 requests on Concurrency Level 10'
            sh 'qual-stress-monitoring/tests/stress_test.sh 1000 10 monMan10 http://sp.alb.sonata-nfv.eu:8000/api/v1/users'
            echo 'Send 1000 requests on Concurrency Level 100'
            sh 'qual-stress-monitoring/tests/stress_test.sh 1000 100 monMan100 http://sp.alb.sonata-nfv.eu:8000/api/v1/users'

        stage 'Stress Mon Manager <-> Prometheus API '
            echo 'Send 1000 requests on Concurrency Level 10'
            sh 'qual-stress-monitoring/tests/stress_test.sh 1000 10 monManPrm10 http://sp.alb.sonata-nfv.eu:8000/api/v1/prometheus/metrics'
            echo 'Send 1000 requests on Concurrency Level 100'
            sh 'qual-stress-monitoring/tests/stress_test.sh 1000 100 monManPrm100 http://sp.alb.sonata-nfv.eu:8000/api/v1/prometheus/metrics'

        stage 'Stress Mon Pushgateway API '
            echo 'Send 10000 requests on Concurrency Level 100'
            sh 'qual-stress-monitoring/tests/post_stress_test.sh 10000 100 monPGW100 http://sp.alb.sonata-nfv.eu:9091/metrics/job/stressTest'
            echo 'Send 10000 requests on Concurrency Level 1000'
            sh 'qual-stress-monitoring/tests/post_stress_test.sh 10000 1000 monPGW1000 http://sp.alb.sonata-nfv.eu:9091/metrics/job/stress'
       

        stage 'Publish the artifact'
            archive (includes: '*.log')
       
        stage 'Notifications'
            echo 'Sending mails'

            mail body: 'project build successful',
                        from: 'sonata-nfv@gmail.com',
                        replyTo: 'sonata-nfv@gmail.com',
                        subject: 'MONITORING SYSTEM Stress test executed',
                        to: 'pkarkazis@synelixis.com'
        }


    catch (caughtError) {
        err = caughtError
        currentBuild.result = "FAILURE"
            mail body: "project build error: ${err}" ,
            from: 'sonata-nfv@gmail.com',
            replyTo: 'sonata-nfv@gmail.com',
            subject: 'MONITORING SYSTEM Stress test failed',
            to: 'pkarkazis@synelixis.com'
        }

    finally {
        /* Must re-throw exception to propagate error */
        if (err) {
            throw err
        }

    }

}
